### PR TITLE
Update circt-ci-build image from testing branch.

### PR DESCRIPTION
**Pull request by youngar**
Update circt-ci-build to:
- be based on Ubuntu 20.04
- install git and cmake from official package repos
- stop installing zlib1g, libcurl, and tcl

### CODE REVIEW

**Comment by youngar** [comment]
You can see the diff for `circt-ci-build/Dockerfile` between this and the `test-ci-build` branch here: https://github.com/circt/images/compare/test-ci-build..dev/youngar/2004#diff-3e0526d7a4390be08a7232dcd1ce1cc2e6b9cdb8ca288d7d99aa499b4dbdd06e.  Ideally the diff should only contain the changes to install clang using `llvm.sh` (which I think it does :+1:)

**Review by mikeurbach — COMMENTED** [review]
The change itself looks good to me, but are we ready to move to Ubuntu 20.04 for this? Were we using 18.04 for compatibility with what we used to have before we used a Docker image for these tests? I know our nightly image uses 20.04 and passes in a variety of configurations for both clang and gcc, so I think it should be fine from my perspective. @teqdruid did you have any other background on this?

**Comment by youngar** [comment]
From what I can tell the docker image currently used by CIRCT CI was built from the branch `test-circt-ci` which is using Ubuntu 20.04.  My guess of what happened is we just missed the final step of merging the changes into branch `trunk`. I don't want to make the situation any worse than I already have so I'll wait for @teqdruid's input here.

**Comment by teqdruid** [comment]
Sorry. Was on vacation.

IIRC, we had issues with the CI pipeline awhile back, which nobody was encountering locally. The easiest solution was to move to a docker image based on 20.04, like the integration CI tests. I was in a tizzy trying to make it work and neglected to merge the "solution" to main (https://github.com/circt/images/compare/test-ci-build). I likely thought it would be temporary until someone fixed the 18.04 build on Docker: https://github.com/llvm/circt/issues/1065

**Review by teqdruid — APPROVED** [review]
lgtm. Thanks!

**Pull request merged**
