### PR TITLE
[integration-test] add click to python deps for sby

### PR DESCRIPTION
**Pull request by unlsycn**
fix https://github.com/llvm/circt/actions/runs/12024212403/job/33520729169

### CODE REVIEW

**Comment by fabianschuiki** [comment]
Very cool, thanks a lot! Would it make sense to add a short test to the sby script that checks whether a simple formal proof runs successfully? Maybe some simple SV file with an assert and a corresponding `*.sby` script that does a formal check of the assert?

**Comment by unlsycn** [comment]
> Very cool, thanks a lot! Would it make sense to add a short test to the sby script that checks whether a simple formal proof runs successfully? Maybe some simple SV file with an assert and a corresponding `*.sby` script that does a formal check of the assert?

I think this is just an image repo and the CIRCT integration test can check it natively.

**Comment by fabianschuiki** [comment]
Sounds good! Looks like a conflict has come up in the Dockerfile. Could you take a look what's going on there before we land this?

**Review by fabianschuiki — APPROVED** [review]
LGTM!

**Pull request merged**
