### PR TITLE
Switch to Static Linking for CIRCT Image

### LINKED ISSUE #2: libMLIRTransforms.so.13git: cannot open shared object file
The nightly image is broken.

```
firtool --version
firtool: error while loading shared libraries: libMLIRTransforms.so.13git: cannot open shared object file: No such file or directory
```

https://github.com/circt/perf/runs/1972527049?check_suite_focus=true

### PR DESCRIPTION
**Pull request by seldridge**
Fixes #2.

### CODE REVIEW

**Review by teqdruid — APPROVED** [review]
LGTM

**Comment by seldridge** [comment]
Hold off on merging this... This doesn't work, yet. (I'm testing locally.)

FYI: I'm switching this to avoid shared linking entirely. The issue is that `build-llvm.sh` needs to do a global install, but it's setup to forcibly install into a build subdirectory which isn't supposed to exist in the final image.

I'll open an issue about setting up CI on PRs, too. (Which would expose the fact that this PR doesn't actually work.)

**Comment by seldridge** [comment]
This is cleaned up to include the old static-linking build script (put inside the Dockerfile). I'm going to go ahead and merge this just so that we have a working image. However, I'm totally fine with more post-commit review.

**Comment by teqdruid** [comment]
Yeah, I'm good with this. The goal of this image is to work -- users don't care how it's linked.

**Pull request merged**
