### PR TITLE
Add OR-Tools to integration_test image.

### PR DESCRIPTION
**Pull request by jopperm**
Google's [OR-Tools](https://developers.google.com/optimization) provide an interface to a variety of open-source and commercial solvers for (I)LP, SAT, etc., which I'd like to *optionally* use in CIRCT Scheduling in the future.

I'll leave this as a draft for now (until there's actual code requiring the libraries), but please let me know if there are any concerns about adding this to the integration_test image.

### CODE REVIEW

**Comment by teqdruid** [comment]
I have no issues including this in the integration test image. OR-Tools looks very useful!

**Comment by lattner** [comment]
I have no concerns either.  Does our cmake already detect it?

**Comment by jopperm** [comment]
> ... no issues ... / ... no concerns ...

Great, thanks!

> Does our cmake already detect it?

No, not yet, I'll link the corresponding PR on the CIRCT side to this one when it does.

**Comment by jopperm** [comment]
I discovered that the OR-Tools project also provides a CMake build, which I'm now using here. Tested locally that the library is picked up by the build-system changes in https://github.com/llvm/circt/pull/2465.

@teqdruid Could you please review, merge and make the release?

**Comment by jopperm** [comment]
Thanks!

**Pull request merged**
