### PR TITLE
Add Quartus to integration tests

### PR DESCRIPTION
**Pull request by darthscsi**
Add Quartus and the license-file-not-needed device family.  Also get modelsim_ase, the crippled questa version (but should be enough for parsing/linting).

### CODE REVIEW

**Comment by teqdruid** [comment]
I would have done this, but those licenses probably don't allow redistribution (which is essentially what a Docker image is). It'd be nice to do this, but I think we need legal clearance from Intel.

It'd be great if they were to have Docker images for Quartus distributions. I've suggested this to them in the past.

**Comment by darthscsi** [comment]
I thought about having the docker file here (as a separate image), but not building it.  Then it wouldn't be redistributed, it would just be a reusable script for installing the tools locally.

**Comment by teqdruid** [comment]
I'm not a lawyer, but I think that's the legally conservative thing to do. You could base the image on the existing one. I have no problem with installing the Quartus package deps in the integration test image.

**Comment by lattner** [comment]
Agreed, we can provide scripts like this, no problem.  We should just be very careful about hosting the resultant docker images.  Should this be an optional part of the image?

**Comment by teqdruid** [comment]
It could be, but I think it's more appropriate to have it be in an image which is based (as in Docker's base image) on the integration test image. Said image could have a bunch of optional proprietary software and would be intended for users to build locally and perhaps host themselves within their organization.

**Comment by teqdruid** [comment]
Somewhat tangentially, I've been tempted to set up a Microsoft internal integration build for CIRCT and have it report the results... Not sure about how the EULA and the reporting steps interact and don't really want to get into it with the lawyers.

It may behoove us (the CIRCT community) at some point to set up meetings with the big EDA players to discuss how we should verify that our RTL works with their tools in an automated and open fashion.

**Pull request closed without merging**
